<?=$this->form->create('', array('class' => 'form-horizontal', 'name' => '2fa')); ?>

<fieldset class="col-sm-5">
    <legend><h2>Two Factor Authentication</h2></legend>

<?php
if(isset($error)) { ?>
<div class="alert alert-dismissible alert-danger col-lg-10 col-lg-offset-1">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <strong>Error!</strong> <?=$error?>
</div>
<?php } ?>

<div class="row">
<div class="alert alert-info col-sm-10 col-sm-offset-1">
To continue, please enter your two factor authentication code.
</div>
</div>

<div class="row">
<div class="form-group">
      <label for="2FA" class="col-lg-4 control-label">Two Factor Code</label>
      <div class="col-lg-4">
        <input class="form-control" id="2FA" name="2FA" placeholder="Code generated by app" type="password">
      </div>
</div>

<div class="form-group">
      <div class="col-lg-2 col-lg-offset-4">
        <button type="submit" id="submit" name="submit" value="submit" class="btn btn-primary">Submit</button>
      </div>
</div>

</div>

</fieldset>
</form>
